
[generation_settings]
	#Biomes in the Overworld are enabled.
	overworld_biomes = true
	#The weighting of biome regions in the Overworld.
	#Range: > 0
	overworld_region_weight = 2
	#Biomes in the Nether are enabled.
	nether_biomes = true
	#The weighting of biome regions in the Nether.
	#Range: > 0
	nether_region_weight = 2
	#Biomes in the End are enabled.
	end_biomes = true
	#The weighting of biome regions in the End.
	#Range: > 0
	end_region_weight = 2

