#Chance for flesh food to add Youkaifying effect for the first time
#Range: 0.0 ~ 1.0
youkaifyingChance = 0.2
#Confusion time when flesh food to add Youkaifying effect for the first time
#Range: 0 ~ 1000000
youkaifyingConfusionTime = 200
#Time for flesh food to add Youkaifying effect
#Range: 0 ~ 1000000
youkaifyingTime = 1200
#Threshold for Youkaifying effect to turn into Youkaified effect
#Range: 0 ~ 1000000
youkaifyingThreshold = 6000
#Youkaified duration once reached
#Range: 0 ~ 1000000
youkaifiedDuration = 24000
#Time for flesh food to add Youkaified effect
#Range: 0 ~ 1000000
youkaifiedProlongation = 6000
#Time for flesh food to add Youkaified effect
#Range: 0.0 ~ 10.0
youkaifiedBoost = 2.0
#Smoothing Healing Factor
#Range: 0.0 ~ 100.0
smoothingHealingFactor = 1.5
#Tea Healing Interval
#Range: 0 ~ 10000
teaHealingPeriod = 60
#Udumbara effect Healing Interval
#Range: 0 ~ 10000
udumbaraHealingPeriod = 60
#Udumbara flowering duration
#Range: 0 ~ 100000
udumbaraDuration = 200
#Udumbara full moon damage reduction
#Range: 0 ~ 100
udumbaraFullMoonReduction = 4

